#!/usr/bin/env python2
from util.Drone import Drone
Jerome = Drone()
Jerome.takeoff()
Jerome.move_to(1.0,0.0,'launch')
Jerome.hover(5)
Jerome.move_to(2.0,1.0,'launch')
Jerome.move_to(0.75,1.0,'launch')
Jerome.move_to(0.0,2.5,'launch')
Jerome.move_to(-0.75,1.0,'launch')
Jerome.move_to(-2.0,1.0,'launch')
Jerome.move_to(-0.5,0.0,'launch')
Jerome.move_to(-1.5,-2.0,'launch')
Jerome.move_to(0.0,-0.5,'launch')
Jerome.move_to(1.5,-2.0,'launch')
Jerome.move_to(1.0,0.0,'launch')
Jerome.hover(5)
Jerome.move_to(0.0,0.0,'launch')
Jerome.hover(3)
Jerome.land()
